### ISSUE TITLE
how to deploy a build version

### ISSUE THREAD

**Issue by ksathyareddy7** [hasura/hello-react#10]
how to deploy a `create-react-app` build version of the app on a hasura cluster?

**Comment by coco98** [comment]
Once you clone the `hasura/hello-react` hub project, just head to the microservice directory. 
There, inside `package.json` change the version of create-react-app to the version you want. And then run npm install!

That should be it :)

**Comment by ksathyareddy7** [comment]
sorry. i meant to say that if i use `create-react-app` to build an app and at last do `npm run build` which gives the production ready static files to be placed on the server, I guess which requires a different project structure than the current one. so how do we deploy this production ready project?

**Comment by coco98** [comment]
Ah! Super easy with: https://hasura.io/hub/project/hasura/hello-nginx
That's an nginx server ready to go. Head to the `microservices/www/app/src` directory, drop your static files there, and `git push hasura master` :)
